- name: Configurar intervalo de backups MariaDB
  hosts: servidores
  become: no

  vars:
    interval: ""

  tasks:

    - name: Validar intervalo
      fail:
        msg: "Debes indicar intervalo (ej: */5 * * * *)"
      when: interval == ""

    - name: Cambiar intervalo del CronJob
      shell: |
        kubectl patch cronjob mariadb-backup \
          -p '{"spec":{"schedule":"{{ interval }}"}}'
      environment:
        KUBECONFIG: "/home/usuario/.kube/config"
