- hosts: local
  become: yes

  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Instalar dependencias
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
        state: present

    - name: Instalar kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Instalar Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube
