- name: Instalación completa de infraestructura
  hosts: servidores
  become: yes

  vars:
    mariadb_root_password: "1234"

  tasks:

    # =========================================================
    # ACTUALIZAR PAQUETES
    # =========================================================

    - name: Actualizar paquetes
      apt:
        update_cache: yes

    # =========================================================
    # INSTALAR DEPENDENCIAS
    # =========================================================

    - name: Instalar dependencias necesarias
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - docker.io
        state: present

    # =========================================================
    # INICIAR DOCKER
    # =========================================================

    - name: Iniciar Docker
      service:
        name: docker
        state: started
        enabled: yes

    # =========================================================
    # INSTALAR KUBECTL
    # =========================================================

    - name: Instalar kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    # =========================================================
    # ASIGNAR PERMISOS
    # =========================================================

    - name: Añadir usuario al grupo docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    
    - name: Reset conexión SSH para aplicar grupo docker
      meta: reset_connection

    # =========================================================
    # INSTALAR MINIKUBE
    # =========================================================

    - name: Instalar Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube
      args:
        creates: /usr/local/bin/minikube

    # =========================================================
    # INICIAR MINIKUBE
    # =========================================================

    - name: Iniciar Minikube
      become: no
      shell: minikube start --driver=docker

    # =========================================================
    # ESPERAR KUBERNETES
    # =========================================================

    - name: Esperar a que Kubernetes esté listo
      become: no
      shell: kubectl get nodes
      register: k8s_result
      retries: 10
      delay: 5
      until: k8s_result.rc == 0

    # =========================================================
    # CREAR SECRET MARIADB
    # =========================================================

    - name: Crear secret de MariaDB
      become: no
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: mariadb-secret
        type: Opaque
        stringData:
          root-password: "{{ mariadb_root_password }}"
        EOF

    # =========================================================
    # DESPLEGAR MARIADB
    # =========================================================

    - name: Desplegar MariaDB
      become: no
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: mariadb
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: mariadb
          template:
            metadata:
              labels:
                app: mariadb
            spec:
              containers:
              - name: mariadb
                image: mariadb:11.4

                ports:
                - containerPort: 3306

                env:
                - name: MARIADB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mariadb-secret
                      key: root-password

                volumeMounts:
                - name: host-backups
                  mountPath: /backup

              volumes:
              - name: host-backups
                hostPath:
                  path: /home/{{ ansible_user }}/mariadb-backups
                  type: DirectoryOrCreate
        EOF

    # =========================================================
    # ESPERAR MARIADB
    # =========================================================

    - name: Esperar MariaDB lista
      shell: kubectl rollout status deployment/mariadb --timeout=180s
      environment:
        KUBECONFIG: "/home/usuario/.kube/config"

    # =========================================================
    # SISTEMA DE BACKUPS
    # =========================================================

    - name: Desplegar CronJob de backups
      become: no
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: batch/v1
        kind: CronJob
      

        metadata:
          name: mariadb-backup

        spec:
          schedule: "*/5 * * * *"

          jobTemplate:
            spec:
              template:
                spec:

                  containers:
                  - name: mariadb-backup
                    image: mariadb:11.4

                    command:
                    - /bin/sh
                    - -c
                    - |
                      set -e

                      echo "Esperando MariaDB..."

                      until mariadb-admin ping -h mariadb-service -u root -p\$MYSQL_ROOT_PASSWORD --silent; do
                        sleep 2
                      done

                      echo "Creando backup..."

                      mariadb-dump \
                        -h mariadb-service \
                        -u root \
                        -p\$MYSQL_ROOT_PASSWORD \
                        --all-databases \
                        > /backup/backup-\$(date +\%Y\%m\%d-\%H\%M\%S).sql

                      echo "Backup terminado"

                    env:
                    - name: MYSQL_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: mariadb-secret
                          key: root-password

                    volumeMounts:
                    - name: backup-volume
                      mountPath: /backup

                  restartPolicy: OnFailure

                  volumes:
                  - name: backup-volume
                    hostPath:
                      path: /home/{{ ansible_user }}/mariadb-backups
                      type: DirectoryOrCreate
        EOF
      environment:
        KUBECONFIG: "/home/usuario/.kube/config"
        
    # =========================================================
    # CREAR SERVICIO SYSTEMD
    # =========================================================

    - name: Crear servicio systemd de Minikube
      copy:
        dest: /etc/systemd/system/minikube.service
        content: |
          [Unit]
          Description=Minikube Kubernetes
          After=docker.service network-online.target
          Requires=docker.service

          [Service]
          Type=oneshot
          User={{ ansible_user }}

          Environment="HOME=/home/{{ ansible_user }}"
          Environment="KUBECONFIG=/home/{{ ansible_user }}/.kube/config"

          ExecStart=/usr/local/bin/minikube start --driver=docker
          ExecStop=/usr/local/bin/minikube stop

          RemainAfterExit=yes

          [Install]
          WantedBy=multi-user.target

    # =========================================================
    # CREAR SERVICIO LOADBALANCER
    # =========================================================

    - name: Exponer MariaDB como LoadBalancer
      become: no
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: Service

        metadata:
          name: mariadb-service

        spec:
          type: LoadBalancer

          selector:
            app: mariadb

          ports:
            - port: 3306
              targetPort: 3306
        EOF
      environment:
        KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

    # =========================================================
    # CREAR SERVICIO MINIKUBE-TUNEL
    # =========================================================

    - name: Crear servicio minikube-tunnel
      copy:
        dest: /etc/systemd/system/minikube-tunnel.service
        content: |
          [Unit]
          Description=Minikube Tunnel
          After=minikube.service
          Requires=minikube.service

          [Service]
          Type=simple
          User=root
          Environment="HOME=/home/{{ ansible_user }}"
          Environment="KUBECONFIG=/home/{{ ansible_user }}/.kube/config"

          ExecStart=/usr/local/bin/minikube tunnel

          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target

    # =========================================================
    # CREAR SERVICIO PORT-FORDWARD
    # =========================================================

    - name: Crear servicio systemd para MariaDB port-forward
      copy:
        dest: /etc/systemd/system/mariadb-portforward.service
        content: |
          [Unit]
          Description=MariaDB Kubernetes Port Forward
          After=minikube.service
          Requires=minikube.service

          [Service]
          Type=simple
          User={{ ansible_user }}

          Environment="KUBECONFIG=/home/{{ ansible_user }}/.kube/config"

          ExecStartPre=/bin/bash -c 'until kubectl get nodes; do sleep 2; done'

          ExecStart=/usr/local/bin/kubectl port-forward svc/mariadb-service 3306:3306 --address 0.0.0.0

          Restart=always
          RestartSec=5

          StandardOutput=journal
          StandardError=journal

          [Install]
          WantedBy=multi-user.target

    # =========================================================
    # RECARGAR SYSTEMD
    # =========================================================

    - name: Recargar systemd
      systemd:
        daemon_reload: yes

    # =========================================================
    # ACTIVAR MINIKUBE
    # =========================================================

    - name: Activar servicio Minikube
      systemd:
        name: minikube
        enabled: yes
        state: started

    # =========================================================
    # ESPERAR KUBERNETES
    # =========================================================

    - name: Esperar a que Kubernetes esté listo
      become: no
      shell: kubectl get nodes
      register: k8s_result
      retries: 10
      delay: 5
      until: k8s_result.rc == 0

    # =========================================================
    # ACTIVAR SERVICIO
    # =========================================================

    - name: Activar minikube-tunnel
      systemd:
        name: minikube-tunnel
        enabled: yes
        state: restarted

    # =========================================================
    # ACTIVAR SERVICIO
    # =========================================================

    - name: Activar minikube-tunnel
      systemd:
        name: mariadb-portforward
        enabled: yes
        state: restarted

    # =========================================================
    # FINAL
    # =========================================================

    - name: Instalación completada
      debug:
        msg: "Infraestructura instalada correctamente"
