- name: Desplegar MariaDB
  hosts: local
  become: no

  vars_prompt:
    - name: mariadb_root_password
      prompt: "Introduce la contraseña de root para MariaDB"
      private: yes

  tasks:

    # ---------------------------
    # SECRET
    # ---------------------------
    - name: Crear secret de MariaDB
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: mariadb-secret
        type: Opaque
        stringData:
          root-password: "{{ mariadb_root_password }}"
        EOF

    # ---------------------------
    # DEPLOYMENT MARIADB
    # ---------------------------
    - name: Desplegar MariaDB
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: mariadb
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: mariadb
          template:
            metadata:
              labels:
                app: mariadb
            spec:
              containers:
              - name: mariadb
                image: mariadb:11.4
                ports:
                - containerPort: 3306

                env:
                - name: MARIADB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mariadb-secret
                      key: root-password

                volumeMounts:
                - name: host-backups
                  mountPath: /backup

              volumes:
              - name: host-backups
                hostPath:
                  path: /home/usuario/mariadb-backups
                  type: DirectoryOrCreate
        EOF

    # ---------------------------
    # SERVICE
    # ---------------------------
    - name: Crear service de MariaDB
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: Service
        metadata:
          name: mariadb-service
        spec:
          selector:
            app: mariadb
          ports:
            - port: 3306
              targetPort: 3306
          type: ClusterIP
        EOF

    # ---------------------------
    # ESPERAR POD LISTO
    # ---------------------------
    - name: Esperar MariaDB lista
      shell: |
        kubectl wait \
        --for=condition=Ready pod \
        -l app=mariadb \
        --timeout=120s
